### ISSUE TITLE
[Compatibility] Better Combat

### ISSUE THREAD

**Issue by Balakay420** [spoorn/DualWield#2]
Is there a way to make it so dual wielding for Better Combat will only work if both weapons have your enchantment? I think this would be a great implication

https://www.curseforge.com/minecraft/mc-mods/better-combat-by-daedelus

**Comment by spoorn** [comment]
This mod (https://www.curseforge.com/minecraft/mc-mods/spoorns-dual-wield) only enables dual wielding if both weapons support the enchantment.  Better Combat adds its own dual wielding system, so you'd have to ask them

It would be unethical and intrusive for me to change the behavior of another mod with my mod like that

**Comment by Balakay420** [comment]
Apologies I wasn't aware of the licensing for that mod. I did say something to the dev of Better Combat, he said it was semantically incompatible
